version: "3.9"
services:
  # blackdagger server
  server:
    image: "erdemozgen/blackdagger:latest"
    build: .
    environment:
      - blackdagger_PORT=8080
      - blackdagger_DAGS=/home/blackdagger/.config/blackdagger/dags
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - blackdagger:/home/blackdagger/.config/blackdagger
      - ./dags/:/home/blackdagger/.config/blackdagger/dags
      - ./data/:/home/blackdagger/.config/blackdagger/data
      - ./logs/:/home/blackdagger/.config/blackdagger/logs
      - ./suspend/:/home/blackdagger/.config/blackdagger/suspend
    #command: ["bash", "/home/blackdagger/startservices.sh"] # Custom command to start the services
    command: ["sh", "-c", "./startservices.sh"]

volumes:
  blackdagger: {}

