version: "3.9"
services:
  # blackdagger server
  server:
    image: "erdemozgen/blackdagger:latest"
    build: .
    environment:
      - BLACKDAGGER_PORT=8080
      - BLACKDAGGER_DAGS=/home/blackdagger/.config/blackdagger/dags
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - blackdagger:/home/blackdagger/.config/blackdagger
      - ./dags:/home/blackdagger/.local/share/blackdagger/dags
      - ./history:/home/blackdagger/.local/share/blackdagger/history
      - ./logs:/home/blackdagger/.local/share/blackdagger/logs
      - ./suspend:/home/blackdagger/.local/share/blackdagger/suspend

volumes:
  blackdagger: {}
