version: "3.9"
services:
  # blackdagger server
  server:
    image: "erdemozgen/blackdagger:latest"
    build: .
    environment:
      - BLACKDAGGER_PORT=8080
      - BLACKDAGGER_DAGS=/home/blackdagger/.config/blackdagger/dags
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - blackdagger:/home/blackdagger/.config/blackdagger
      - ./dags:/home/blackdagger/.config/blackdagger/dags
      - ./data:/home/blackdagger/.config/blackdagger/data
      - ./logs:/home/blackdagger/.config/blackdagger/logs
      - ./suspend:/home/blackdagger/.config/blackdagger/suspend
    command: ["sh", "-c", "/usr/local/bin/startservices.sh"]

volumes:
  blackdagger: {}
