name: Release

on:
  push:
    branches:
      - main
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Installing swagger
        run: |
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Set up yarn
        run: npm install --global yarn

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Yarn install
        run: yarn install
        working-directory: ui

      - name: Build web UI
        run: yarn build
        working-directory: ui

      - name: Copy web assets
        run: |
          cp ui/dist/*.js ./service/frontend/assets/
          cp ui/dist/*.woff ./service/frontend/assets/
          cp ui/dist/*.woff2 ./service/frontend/assets/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.BLACKDAGGER_SECRET}}